export const fontFamilies = {
  heading: 'Fraunces_700Bold',
  body: 'DMSans_400Regular',
  bodyMedium: 'DMSans_600SemiBold',
  bodyBold: 'DMSans_700Bold',
} as const;

export const tokens = {
  colors: {
    primary: '#E85D4F',
    primaryHover: '#B83A32',
    primarySoft: '#FFE0DC',
    background: '#F8F6F2',
    surface: '#FFFDF9',
    surfaceSoft: '#FFF0ED',
    text: '#2D2422',
    muted: '#8C7A77',
    outline: '#E0BFBB',
    accent: '#F4A261',
    accentSoft: '#FFE7CF',
    success: '#7BAE7F',
    error: '#BA1A1A',
    navActive: '#5A3934',
    navInactive: '#B29A95',
    cardTranslucent: 'rgba(255, 253, 249, 0.88)',
    cardStrong: '#FFF9F6',
    bloomTop: '#FEE1D9',
    bloomBottom: '#FFF0E2',
    onPrimary: '#FFF8F5',
    onAccent: '#FFF9F3',
    overlay: 'rgba(45, 36, 34, 0.18)',
    input: '#FFF9F6',
    disabled: '#F7EEE9',
    disabledText: '#C6B4AE',
  },
  spacing: {
    xs: 8,
    sm: 16,
    md: 24,
    lg: 32,
    xl: 40,
    xxl: 48,
  },
  radius: {
    control: 8,
    card: 16,
    modal: 24,
    hero: 32,
    pill: 999,
  },
  typography: {
    headingFamily: fontFamilies.heading,
    bodyFamily: fontFamilies.body,
    bodyMediumFamily: fontFamilies.bodyMedium,
    bodyBoldFamily: fontFamilies.bodyBold,
    title: 32,
    section: 24,
    body: 15,
    caption: 12,
    button: 16,
  },
  shadow: {
    shadowColor: '#E85D4F',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },
} as const;
